# Generated by Django 5.2.6 on 2025-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='books/', verbose_name='Обложка!')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги!')),
                ('description', models.TextField(verbose_name='Описание книги!')),
                ('quatity_page', models.PositiveIntegerField(default=1, verbose_name='Количество страниц')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Укажите автора!')),
                ('book_audio', models.URLField(verbose_name='Укажите ссылку с ютуба!')),
                ('created_at', models.CharField(verbose_name='Дата создания книги!')),
            ],
        ),
    ]
