# Generated by Django 5.2.6 on 2025-10-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
    ]
