# Generated by Django 5.2.6 on 2025-10-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нрсултан', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Туриста',
                'verbose_name_plural': 'Туристы',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_at', models.CharField(default='Япония', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='books.person')),
            ],
            options={
                'verbose_name': 'тур',
                'verbose_name_plural': 'туры',
            },
        ),
    ]
