# Generated by Django 5.2.6 on 2025-10-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_person_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='choice_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='mark_book',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='review_text',
        ),
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.TextField(default='Прикольная книга', verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания книги!'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='Нурсултан', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_at',
            field=models.CharField(default='Япония', max_length=100, verbose_name='Место тура'),
        ),
    ]
