# Generated by Django 5.2.6 on 2025-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0002_alter_movie_options_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
