# Generated by Django 5.2.6 on 2025-10-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_customer_delete_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
    ]
